[package]
name = "The Search for the White Wave"
description = "A scientific expedition headed into the Sea of Ghosts has failed to report on their progress. An investigator from the Imperial Navy has been dispatched to locate the White Wave and is looking for a hand. Join his crew to unravel what happened to the White Wave in the frozen northern waters..."
homepage = "https://www.nexusmods.com/morrowind/mods/52301"
authors = [
	"Melchior Dahrk",
]
version = "1.4"

[dependencies]
assets = [ 
	"TheSearchForTheWhiteWave.ESP",
]

[dependencies.mods."OAAB_Data"]
version = ">=2.2.2"
url = "https://www.nexusmods.com/morrowind/mods/49042"

[dependencies.mods."Tamriel_Data"]
plugin = "Tamriel_Data.esm"
url = "https://www.nexusmods.com/morrowind/mods/44537"